# Generated by Django 4.1.7 on 2023-04-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='mail_id',
            new_name='mailid',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='membername',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='memberpic',
        ),
    ]
